spring:
    datasource:
        url: jdbc:mysql://localhost:3306/fxedu_dev
        username: fxedu_dev_user
        password: F*angXiaDe*v
        driver-class-name: com.mysql.cj.jdbc.Driver

    quartz:
        scheduler-name: fxeduSchedulerDev
        job-store-type: jdbc
        jdbc:
            initialize-schema: always
        properties:
            org:
                quartz:
                    jobStore:
                        isClustered: false
                        tablePrefix: QRTZ_
                    threadPool:
                        threadCount: 5

mybatis-plus:
    mapper-locations: classpath*:mapper/**/*.xml
    type-aliases-package:
        com.fangxia.fxedu.model.eo,
        com.fangxia.fxedu.model.dto,
        com.fangxia.fxedu.model.vo

logging:
    level:
        root: DEBUG
        com.fangxia.fxedu: DEBUG
    pattern:
        console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger - %msg%n"
